# Generated by Django 4.2 on 2025-11-10 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Issue Title')),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('category', models.CharField(choices=[('ROAD', 'Roads & Infrastructure'), ('SANI', 'Sanitation & Waste'), ('WATR', 'Water & Drainage'), ('SAFE', 'Public Safety'), ('CIVC', 'Civic Amenities & Public Spaces')], default='ROAD', max_length=4, verbose_name='Category')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('status', models.CharField(choices=[('REP', 'Reported'), ('REV', 'Under Review'), ('IPR', 'In Progress'), ('RES', 'Resolved'), ('REJ', 'Rejected')], default='REP', max_length=3, verbose_name='Current Status')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
